#pragma once
#define OBJECT_BUILDING 1
#define OBJECT_CHARACTER 2
#define OBJECT_BULLET 3
#define OBJECT_ARROW 4

#define LEVEL_BUILDING 0.1
#define LEVEL_CHARACTER 0.2
#define LEVEL_BULLET 0.3
#define LEVEL_ARROW 0.3